### ISSUE TITLE
how to debug a model

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#109] opened 2021-04-05 00:52 UTC
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/pymc3_howto/howto_debugging.ipynb
Reviewers:

> The sections below may still be pending. If so, the issue is still available, it simply doesn't
> have specific guidance yet. Please refer to [this overview of updates](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)

## Known changes needed
Changes listed in this section should all be done at some point in order to get this
notebook to a "Best Practices" state. However, these are probably not enough!
Make sure to thoroughly review the notebook and search for other updates.

### General updates
*

### ArviZ related
*

## Changes for discussion
Changes listed in this section are up for discussion, these are ideas on how to improve
the notebook but may not have a clear implementation, or fix some know issue only partially.

### General updates
*

### ArviZ related
*

**Comment by kuvychko** [comment] 2022-07-23 20:45
I'd like to take this one. @OriolAbril, you can assign it to me (not sure if that's part of the process). Thanks!

**Comment by reshamas** [comment] 2022-07-23 21:24
@kuvychko There are a couple of ways to "claim" an issue:  
1.  on issue, you can say "I am working on this"
2. you can type "take" and it should assign it to you.

**Comment by kuvychko** [comment] 2022-07-23 23:57
/take

@reshamas  - thank you!!

**Comment by kuvychko** [comment] 2022-07-23 23:57
take

**Comment by kuvychko** [comment] 2022-07-23 23:58
"take"

**Comment by reshamas** [comment] 2022-07-24 11:52
@kuvychko Sorry to misinform. This works in the scikit-learn repo, so I assumed it was a default GitHub feature. 

Ref:  https://scikit-learn.org/stable/developers/contributing.html#contributing-code
Example:  
```
One easy way to find an issue to work on is by applying the “help wanted” label in your search. This lists all the issues that have been unclaimed so far. In order to claim an issue for yourself, please comment exactly /take on it for the CI to automatically assign the issue to you.
```

I assume it needs to be set up for this repo.

**Comment by kuvychko** [comment] 2022-07-24 13:25
@reshamas - no worries, thank you!

I started working on this notebook, and ran into an issue. The example used no longer works as intended: with `step = pm.Metropolis()` sample fails immediately with a very clear exception message:

`SamplingError: Initial evaluation of model at starting point failed!
Starting values:
{'mu': array(0.), 'sd': array(0.)}

Initial evaluation results:
{'mu': -0.92, 'sd': -0.92, 'obs': -inf}`

This obviates the need to print out intermediate values. If I use a default NUTS sampler it works just fine even with the wonky priors. Any thoughts on a different example to show use of `aesara.printing.Print`? Or should this notebook be removed from examples?

**Comment by OriolAbril** [comment] 2022-07-25 18:51
There are always examples of broken models on Discourse. I'll try to browse a bit to find one. It is nice to see the error message is so much nicer now that the "debigging for wrong initial point issues" is no longer needed! 

I do think the notebook is still needed though, and I am confident we'll find another model to show how to debug, maybe some model that has problematic shapes for example? 

Or a good starting point but bad constraints on the parameters (which might even work on the current notebook), what happens for example if you set `sd = pm.Normal("sd", mu=1, sigma=1)` or with `mu=2` instead of 0? Then the starting point should work (IIRC the starting point is the mean, and most values will also work, but the probability of <0 sd is not 0, so we are bound to run into issues anyways I think.

**Comment by kuvychko** [comment] 2022-07-25 23:05
@OriolAbril  - indeed, new exception message is excellent, very neat improvement! Thanks for your advice, I'll experiment with bad priors, and keep working through this notebook. If you find a good example please let me know! By any chance, do you know who is the original author of this notebook? It doesn't have that info.

**Comment by ricardoV94** [comment] 2022-07-26 05:15
One way printing is useful is if you have intermediate operations between variables, so that you don't know the exact value that is leading to problems.

**Comment by kuvychko** [comment] 2022-07-26 16:33
@ricardoV94 - thanks, I'll experiment with your example. Question: what if instead of using aesara.printing.Print, you route intermediate values to a Deterministic variable? Seems like both methods should work in a similar way.

**Comment by ricardoV94** [comment] 2022-07-26 16:40
The model will likely fail without any way of seeing what the value of the deterministic was.

**Comment by kuvychko** [comment] 2022-07-31 03:10
Hi everybody, I ran into an issue trying to commit my new version of the notebook. During pre-commit a copy of the notebook in md format is created in the same folder (examples/howto/howto_debugging.md) instead of myst_nbs/howto/howto_debugging.myst.md, therefore jupytext check is filing. Any advice on how to fix this?

**Comment by OriolAbril** [comment] 2022-07-31 03:21
does the ipynb file have some custom jupytext metadata that is overriding the project configuration?

**Comment by kuvychko** [comment] 2022-07-31 03:51
I made no changes to the metadata. Here how it looks like for howto_debugging.ipynb (problem notebook):

```
{
  "kernelspec": {
    "name": "python3",
    "display_name": "Python 3 (ipykernel)",
    "language": "python"
  },
  "jupytext": {
    "formats": "ipynb,md:myst"
  },
  "language_info": {
    "name": "python",
    "version": "3.10.5",
    "mimetype": "text/x-python",
    "codemirror_mode": {
      "name": "ipython",
      "version": 3
    },
    "pygments_lexer": "ipython3",
    "nbconvert_exporter": "python",
    "file_extension": ".py"
  }
}
```

and here is the metadata for spline.ipynb (myst.md export worked for it). It has the extra "interpreter" bit and a hash value.

```
{
  "interpreter": {
    "hash": "87bd0c5c372351de506bff22b267ffb5c759e6b8276deaa6e4203adc4dc0d335"
  },
  "kernelspec": {
    "name": "python3",
    "display_name": "Python 3 (ipykernel)",
    "language": "python"
  },
  "language_info": {
    "name": "python",
    "version": "3.10.5",
    "mimetype": "text/x-python",
    "codemirror_mode": {
      "name": "ipython",
      "version": 3
    },
    "pygments_lexer": "ipython3",
    "nbconvert_exporter": "python",
    "file_extension": ".py"
  }
}
```

**Comment by OriolAbril** [comment] 2022-07-31 04:10
I don't know what the interpreter thing but I think it is not relevant here. The key part are these lines:

```
"jupytext": {
    "formats": "ipynb,md:myst"
  },
```

which should not be there as they are overriding the project level jupytext config.

**Comment by kuvychko** [comment] 2022-07-31 13:56
D'oh! @OriolAbril - thanks, I fixed it (my bad!) Pull request is in :-).

**Comment by kuvychko** [comment] 2022-07-31 15:35
@OriolAbril  - a question on hyperlinks in notebooks. In splines notebook there are several hyperlinks to externals pages, and jupytext check was happy. In my initial version of "how to debug" I had two hyperlinks, one to [Aesara doc](https://aesara.readthedocs.io/en/latest/tutorial/debug_faq.html) and another to github repo of Lindley Lentati. Both properly formatted (same as in passing splines notebook). pre-commit was failing due to presence of these links. Since both links were not critical to the notebook I removed them. but I'd like to understand hyperlink check criteria for my future contributions - can you explain what's the logic there, or point me in the right direction if it's documented somewhere?

**Comment by OriolAbril** [comment] 2022-07-31 17:51
I thought we had updated the name of that check. There is nothing inherently wrong with external links, there can be as many external links as you want. The check is against urls that should instead be sphinx references. In this case, the link to the Aesara documentation should not be a url but a sphinx cross-reference instead. I added a section on how to use sphinx-cross references in my pymc-examples webinar material: https://pymc-data-umbrella.xyz/en/latest/about/contributing_to_documentation/docs_presentation.html#cross-referencing-roles.

The reason for this is that sphinx-cross references are much more robust. To generate a link to the api docs for `aesara.printing.Print` you can use `` {class}`aesara.printing.Print` `` which sphinx renders as a url to the correct documentation. If using sphinx cross-references, if the aesara docs move from `aesara.readthedocs.io` to `aesara.ai` for example, we will only need to modify one line in `conf.py` and _all links to aesara docs in all notebooks will work again_. If the documentation is restructured (like we just did with pymc one for example) changing the specific uls in the API section, regenerating the pymc-examples website alone will be enough to fix all the links. If instead we used urls, any change would require going notebook per notebook, url per url in order to fix them.

This becomes even more relevant for internal cross-references. One can read https://www.pymc.io/projects/examples/en/latest (default, to see the lasest state of all notebooks) or https://www.pymc.io/projects/examples/en/2022.01.0 (frozen snapshot of the website, to see what was the state of the example gallery in January, when most notebooks run on v3 for example). If we use urls for these kind of references, it is impossible for our own website to be coherent. The url hardcodes the version on which to link, the sphinx cross-references do not and will always link to the version being read; to put an example, if the spline notebook links to the debugging one, and uses sphinx cross-references, the version of the example gallery I am reading won't change under my feet inadvertedly when I click on the link.

**Comment by kuvychko** [comment] 2022-07-31 20:49
@OriolAbril - really appreciate the details, thanks!!! sphinx write-up is really helpful, too. I didn't realize that aesara falls under the same rubric as pymc in terms of documentation, which makes total sense! looks like a well thought-out system.

**Comment by OriolAbril** [comment] 2022-07-31 21:21
You can see in the pre-commit config which are the websites whose urls are "forbidden": https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml#L87-L97

**Closed** 2022-08-17 01:45 UTC
Labels: tracker id
