### ISSUE TITLE
Merge Cox survival example with Bayesian survival analysis example

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc-examples#275] opened 2022-01-30 21:35 UTC
While the Cox survival notebook is a nice example of a ported BUGS model, there is no supporting documentation in the notebook. Moreover, there is already a Cox example in Austin's comprehensive Bayesian survival analysis notebook. I propose 3 alternatives:

1. Integrate the Cox example into the Bayesian survival analysis notebook
2. Turn the Cox example into a `.py` script
3. Flesh out the Cox notebook with supporting narrative

I'm not personally in favor of the third option, as it is a lot of work for what is mostly a redundant example, but I want to get feedback before choosing one and updating.

**Comment by OriolAbril** [comment] 2022-02-01 14:42
I would also argue against option 2, python files are too hard to find and I think we should probably see which ones to move into notebooks and get rid of the others. 

Given that the survival analysis notebook is already quite long, I'd like to propose a different option, splitting the notebook (in two or more) with a notebook being an [explanation](https://diataxis.fr/explanation/) about survival analysis and different approaches and the others [how to guides](https://diataxis.fr/how-to-guides/) on writing a specific type of survival model with pymc, one of them being the cox one? Note that I haven't gone through either notebook carefully and I'm not sure how feasible this proposal is.

**Comment by cfonnesbeck** [comment] 2022-02-02 17:36
We have several non-notebook examples already. One (not me) could argue that not everyone likes examples in notebook format. If we don't want additional python scripts, then I agree we should be converting/removing the existing ones.

There's nothing inherently wrong with a long notebook, particularly for a complicated topic like survival modeling. This is analogous to vignettes in the R world.  I don't think integrating the Cox notebook would make it much longer, as there is already a Cox model in there; it would mostly be cherry-picking the good parts to modify the existing one.

**Comment by OriolAbril** [comment] 2022-02-02 23:08
> We have several non-notebook examples already. One (not me) could argue that not everyone likes examples in notebook format. If we don't want additional python scripts, then I agree we should be converting/removing the existing ones.

in my opinion, any python/jupyter differences are completely eclipsed by the fact that python scripts are not on the website. GitHub shows traffic for top pages for the last 14 days. The last page to make it today is the BART PR, with a total of 11 views (from 3 unique visitors only). No pyhton script makes the list. Given how we have things set up now, python script examples are as good as gone.

> There's nothing inherently wrong with a long notebook

I agree with this too, but I see a lot of value in diataxis, and I think many notebooks, including this one after skimming could benefit from it, especially now that we have tags and categories. Users might come to the docs with virtually no knowledge of survival analysis, but they might also come with a deep understanding of the subject already, searching only for documentation on how to implement a specific model. If we follow diataxis, the first type of users will need to read a couple of shorter notebooks instead of a single one (and with categories and referencing between the two it is easy to direct them to the "initial" notebook if they first land somehow on the advanced one), the second type will have it much easier to find the info they need. Even the 1st type find the info they need faster arguably, if they don't know about survival analysis, it might not even be the type of model they want and could realize/learn that without investing into learning how to use them with PyMC.

Note: using diataxis can be a lot of work, and it should never be something to follow always and without exceptions (while numpydoc style in docstrings should clearly be followed always without exception for example). I think more of it as a guide to take into account when restructuring content, which is why I mentioned it.

**Comment by drbenvincent** [comment] 2022-04-08 15:41
My thoughts...
- Propose deleting the Cox notebook completely. It would probably be harder for someone to flesh it out than create a Cox example from scratch.
- I like @OriolAbril's diataxis suggestion. But yes, this can take a lot of effort. So for now we maybe keep the Bayesian survival analysis notebook and evolve ourselves towards having a beginner's intro to survival modelling complimented with concise examples of specific univariate and regression models

**Comment by cfonnesbeck** [comment] 2022-04-08 16:16
I think ditching it is the way to go, particularly since there is mention of the proportional hazards model at the end of the survival notebook.

**Comment by drbenvincent** [comment] 2022-04-09 11:30
I'm just starting on a PR to remove this...

**Comment by drbenvincent** [comment] 2022-04-09 21:32
Can potentially close this issue now and come back to further survival analysis notebooks in the future?

**Closed** 2022-04-09 22:01 UTC
Labels: proposal
